spring.application.name=gestion-excepciones
# Configuracion del puerto del servidor web
server.port=8080

# Conexion a la base de datos real en Docker
spring.datasource.url=jdbc:postgresql://db-usuarios:5432/pokemon_db
spring.datasource.username=user_admin
spring.datasource.password=1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Para poder ver las consultas en la consola
spring.jpa.show-sql=true
# Configuracion de Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

