services:
  db-usuarios:
    image: postgres:15
    container_name: db-usuarios
    environment:
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"
    volumes:
      - ./datos_db:/var/lib/postgresql/data
    networks:
      - red_pokemon

  python-api:
    build: ./api_python
    container_name: python-api
    # AÑADIMOS LA DIRECTIVA PORTS AQUÍ PARA QUE POSTMAN PUEDA ENTRAR:
    ports:
      - "5000:5000"
    depends_on:
      - db-usuarios
    networks:
      - red_pokemon

  java-app:
    build: ./gestion-excepciones
    container_name: java-app
    ports:
      - "8080:8080"
    environment:
      - PYTHON_URL=http://python-api:5000/api
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-usuarios:5432/pokemon_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=${GMAIL_USER}
      - SPRING_MAIL_PASSWORD=${GMAIL_PASS}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - db-usuarios
      - python-api
      - rabbitmq
    networks:
      - red_pokemon

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"   # Puerto de conexión interna
      - "15672:15672" # Puerto del panel de control web (¡Para verlo en la presentación!)
    restart: always
    networks:
      - red_pokemon

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube-server
    ports:
      - "9000:9000"
    networks:
      - red_pokemon

networks:
  red_pokemon:
    driver: bridge