version: '3.8'

services:
  # 1. LA BASE DE DATOS (PostgreSQL)
  db-usuarios:
    image: postgres:15
    container_name: db-usuarios
    environment:
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - ./datos_db:/var/lib/postgresql/data
    networks:
      - red_pokemon

  # 2. LA API DE PYTHON
  python-api:
    build: ./api_python
    volumes:
      - ./api_python:/app
    ports:
      - "5000:5000"
    networks:
      - red_pokemon

  # 3. LA APP DE JAVA
  java-app:
    build: ./gestion-excepciones
    ports:
      - "8080:8080"
    environment:
      - PYTHON_URL=http://python-api:5000/api
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-usuarios:5432/pokemon_db
    depends_on:
      - db-usuarios
      - python-api
    networks:
      - red_pokemon

networks:
  red_pokemon:
    driver: bridge